# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        MainWindow.setWindowIcon(QtGui.QIcon('assets/icon.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")


        self.distance_label = QtWidgets.QLabel(self.centralwidget)
        self.distance_label.setObjectName("distance_label")
        self.gridLayout.addWidget(self.distance_label, 2, 1, 1, 1)
        self.reflection_label = QtWidgets.QLabel(self.centralwidget)
        self.reflection_label.setObjectName("reflection_label")
        self.gridLayout.addWidget(self.reflection_label, 1, 1, 1, 1)


        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.wavelength_label = QtWidgets.QLabel(self.centralwidget)
        self.wavelength_label.setMaximumSize(QtCore.QSize(100, 20))
        self.wavelength_label.setObjectName("wavelength_label")
        self.gridLayout.addWidget(self.wavelength_label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.n_label = QtWidgets.QLabel(self.centralwidget)
        self.n_label.setObjectName("n_label")
        self.gridLayout.addWidget(self.n_label, 3, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 3, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plot1Grid = QtWidgets.QGridLayout()
        self.plot1Grid.setObjectName("plot1Grid")
        self.horizontalLayout.addLayout(self.plot1Grid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фабри Перо"))
        self.distance_label.setText(_translate("MainWindow", "__"))
        self.reflection_label.setText(_translate("MainWindow", "__"))
        self.label_3.setText(_translate("MainWindow", "Расстояние между зеркалами [мм]"))
        self.wavelength_label.setText(_translate("MainWindow", "__"))
        self.label_2.setText(_translate("MainWindow", "Коэффициент отражение зеркал"))
        self.label.setText(_translate("MainWindow", "Длина волны [нм]"))
        self.label_4.setText(_translate("MainWindow", "Коэффициент преломления среды резонатора"))
        self.n_label.setText(_translate("MainWindow", "__"))
